FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/bosch-bar/index.html
COPY icon.png /usr/share/nginx/html/bosch-bar/icon.png
COPY hero.png /usr/share/nginx/html/bosch-bar/hero.png
COPY dashboard.png /usr/share/nginx/html/bosch-bar/dashboard.png
