FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/bike-bar/index.html
COPY icon.png /usr/share/nginx/html/bike-bar/icon.png
COPY hero.png /usr/share/nginx/html/bike-bar/hero.png
COPY dashboard.png /usr/share/nginx/html/bike-bar/dashboard.png
COPY install.sh /usr/share/nginx/html/bike-bar/install.sh
