server {
    listen 8080;
    root /usr/share/nginx/html;
    port_in_redirect off;
    absolute_redirect off;

    location /bike-bar/install.sh {
        default_type text/plain;
    }

    location /bike-bar {
        try_files $uri $uri/ /bike-bar/index.html;
    }
}
